server:
  port: 8081

spring:
  application:
    name: auth-service
  cloud:
    openfeign:
      client:
        config:
          users-service:
            connect-timeout: 2000
            read-timeout: 5000
            logger-level: basic
      compression:
        request:
          enabled: true
        response:
          enabled: true

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always # when_authorized

security:
  jwt:
    issuer: "auth-service"
    audience: "irisinfinity"
    access-ttl-minutes: 15
    refresh-ttl-days: 7
    secret: ${JWT_SECRET:dev-access-secret-at-least-32-chars-123456}
    refresh-secret: ${JWT_REFRESH_SECRET:dev-refresh-secret-at-least-32-chars-123456}