server:
  port: 8083

spring:
  application:
    name: events-service

security:
  jwt:
    secret: ${JWT_SECRET:dev-access-secret-at-least-32-chars-123456}
  permit:
    - method: GET
      patterns:
        - /actuator/health

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: *
  endpoint:
    health:
      show-details: always # when_authorized