spring:
  application:
    name: events-service

server:
  tomcat:
    basedir: logs/${spring.application.name}
    accesslog:
      enabled: true
      directory: .
      pattern: '%h %l %u %t "%r" %s %b %D'