spring:
  application:
    name: users-service
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082
  tomcat:
    basedir: .logs/${spring.application.name}
    accesslog:
      enabled: true
      directory: .
      pattern: '%h %l %u %t "%r" %s %b %D'

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always # when_authorized