server:
  port: 8082

spring:
  application:
    name: users-service
  datasource:
    url: jdbc:postgresql://localhost:5432/users_db
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

security:
  jwt:
    issuer: auth-service
    audience: irisinfinity
    secret: ${JWT_SECRET:dev-access-secret-at-least-32-chars-123456}

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
