version: "3.9"

services:
  prometheus:
    image: prom/prometheus:v2.55.0
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prom_data:/prometheus
    ports:
      - "9091:9090"           # Prometheus UI → http://localhost:9091
    networks: [ monitoring ]

  grafana:
    image: grafana/grafana:10.4.6
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"           # Grafana UI → http://localhost:3000
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks: [ monitoring ]

networks:
  monitoring:
    driver: bridge

volumes:
  prom_data:
  grafana_data: