server:
  port: 8080

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  security:
    user:
      name: prom
      password: '{noop}prom123'
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - AddResponseHeader=X-Powered-By, IrisInfinity Gateway Service
          httpclient:
            connect-timeout: 3000
            response-timeout: 10s
            pool:
              metrics: true
          metrics:
            enabled: true
            prefix: spring.cloud.gateway
            tags:
              app: ${spring.application.name}
              instance: ${HOSTNAME:local}
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates: [ Path=/auth/** ]
            - id: users-service
              uri: lb://users-service
              predicates: [ Path=/users/** ]
              filters:
                - PrefixPath=/api/v1
            - id: events-service
              uri: lb://events-service
              predicates: [ Path=/events/** ]
              filters:
                - PrefixPath=/api/v1

management:
  server:
    port: 9080
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,gateway
  endpoint:
    prometheus:
      access: unrestricted
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
        spring.cloud.gateway.requests: true

security:
  jwt:
    issuer: auth-service
    audience: irisinfinity
    secret: ${JWT_SECRET:dev-access-secret-at-least-32-chars-123456}

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}