server:
  port: 8080

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - AddResponseHeader=X-Powered-By, IrisInfinity Gateway Service
          httpclient:
            connect-timeout: 3000
            response-timeout: 10s
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates: [ Path=/auth/** ]
            - id: users-service
              uri: lb://users-service
              predicates: [ Path=/users/** ]
              filters:
                - PrefixPath=/api/v1
            - id: events-service
              uri: lb://events-service
              predicates: [ Path=/events/** ]
              filters:
                - PrefixPath=/api/v1

security:
  jwt:
    issuer: auth-service
    audience: irisinfinity
    secret: ${JWT_SECRET:dev-access-secret-at-least-32-chars-123456}

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway