server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${GITHUB_URI}
          search-paths:
            - '{profile}'
          username: ${GITHUB_USER}
          password: ${GITHUB_TOKEN}
          clone-on-start: true
          force-pull: true
          timeout: 10

management:
  endpoints.web.exposure.include: health,info